//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LystenApi.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppAccessToken
    {
        public int TokenId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AuthToken { get; set; }
        public Nullable<System.DateTime> IssuedOn { get; set; }
        public Nullable<System.DateTime> ExpiresOn { get; set; }
        public string DeviceType { get; set; }
    
        public virtual User_Master User_Master { get; set; }
    }
}
