//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LystenApi.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country_Master
    {
        public Country_Master()
        {
            this.City_Master = new HashSet<City_Master>();
            this.State_Master = new HashSet<State_Master>();
            this.User_Master = new HashSet<User_Master>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<City_Master> City_Master { get; set; }
        public virtual ICollection<State_Master> State_Master { get; set; }
        public virtual ICollection<User_Master> User_Master { get; set; }
    }
}
