//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LystenApi.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.UserGroupMappings = new HashSet<UserGroupMapping>();
            this.WebSocketSessionDbs = new HashSet<WebSocketSessionDb>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public Nullable<int> GroupTypeId { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual GroupType GroupType { get; set; }
        public virtual User_Master User_Master { get; set; }
        public virtual ICollection<UserGroupMapping> UserGroupMappings { get; set; }
        public virtual ICollection<WebSocketSessionDb> WebSocketSessionDbs { get; set; }
    }
}
