//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LystenApi.Db
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LystenEntities : DbContext
    {
        public LystenEntities()
            : base("name=LystenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnswerGroup> AnswerGroups { get; set; }
        public DbSet<Answer> Answers { get; set; }
        public DbSet<AppAccessToken> AppAccessTokens { get; set; }
        public DbSet<BraintreeCustomerMapping> BraintreeCustomerMappings { get; set; }
        public DbSet<Calling_Request> Calling_Request { get; set; }
        public DbSet<CallingPriceMaster> CallingPriceMasters { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<CategoryImageEvent> CategoryImageEvents { get; set; }
        public DbSet<City_Master> City_Master { get; set; }
        public DbSet<Country_Master> Country_Master { get; set; }
        public DbSet<EmailAccount> EmailAccounts { get; set; }
        public DbSet<EmailTemplate> EmailTemplates { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Favourite> Favourites { get; set; }
        public DbSet<GenderMaster> GenderMasters { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<GroupType> GroupTypes { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessageRecipient> MessageRecipients { get; set; }
        public DbSet<MessageRequest> MessageRequests { get; set; }
        public DbSet<Question> Questions { get; set; }
        public DbSet<QuestionsCategoryMapping> QuestionsCategoryMappings { get; set; }
        public DbSet<ReminderFrequency> ReminderFrequencies { get; set; }
        public DbSet<ReportUser> ReportUsers { get; set; }
        public DbSet<RoleMaster> RoleMasters { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<State_Master> State_Master { get; set; }
        public DbSet<Topic> Topics { get; set; }
        public DbSet<User_Master> User_Master { get; set; }
        public DbSet<UserCategoryMapping> UserCategoryMappings { get; set; }
        public DbSet<UserGroupMapping> UserGroupMappings { get; set; }
        public DbSet<UserQuestionSubscribe> UserQuestionSubscribes { get; set; }
        public DbSet<WebSocketSessionDb> WebSocketSessionDbs { get; set; }
        public DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
