//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LystenApi.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageRequest
    {
        public int Id { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public Nullable<bool> IsAccept { get; set; }
        public Nullable<bool> IsReject { get; set; }
        public Nullable<bool> IsRequested { get; set; }
    
        public virtual User_Master User_Master { get; set; }
        public virtual User_Master User_Master1 { get; set; }
    }
}
