//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LystenApi.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageRecipient
    {
        public int Id { get; set; }
        public Nullable<int> RecipientId { get; set; }
        public Nullable<int> RecipientGroupId { get; set; }
        public Nullable<int> MessageId { get; set; }
        public Nullable<bool> IsRead { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual User_Master User_Master { get; set; }
    }
}
