//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LystenApi.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleMaster
    {
        public int RoleID { get; set; }
        public string Name { get; set; }
        public bool Status { get; set; }
        public System.DateTime Createddate { get; set; }
        public int Createdby { get; set; }
        public System.DateTime Modifydate { get; set; }
    }
}
