//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LystenApi.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Master
    {
        public User_Master()
        {
            this.Answers = new HashSet<Answer>();
            this.AppAccessTokens = new HashSet<AppAccessToken>();
            this.BraintreeCustomerMappings = new HashSet<BraintreeCustomerMapping>();
            this.Calling_Request = new HashSet<Calling_Request>();
            this.Calling_Request1 = new HashSet<Calling_Request>();
            this.Events = new HashSet<Event>();
            this.Groups = new HashSet<Group>();
            this.Messages = new HashSet<Message>();
            this.MessageRecipients = new HashSet<MessageRecipient>();
            this.MessageRequests = new HashSet<MessageRequest>();
            this.MessageRequests1 = new HashSet<MessageRequest>();
            this.Questions = new HashSet<Question>();
            this.ReportUsers = new HashSet<ReportUser>();
            this.ReportUsers1 = new HashSet<ReportUser>();
            this.UserCategoryMappings = new HashSet<UserCategoryMapping>();
            this.UserGroupMappings = new HashSet<UserGroupMapping>();
            this.UserQuestionSubscribes = new HashSet<UserQuestionSubscribe>();
            this.WebSocketSessionDbs = new HashSet<WebSocketSessionDb>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string SessionId { get; set; }
        public string Displayname { get; set; }
        public string Address { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string DeviceToken { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<System.DateTime> Modifydate { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public string CollegeUniversity { get; set; }
        public string Degree { get; set; }
        public string Occupation { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> IsDisclaimer { get; set; }
        public string TimeZone { get; set; }
        public string DeviceType { get; set; }
        public string SSN { get; set; }
        public string Skill { get; set; }
        public string DateOfBirth { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public string PostalCode { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual ICollection<AppAccessToken> AppAccessTokens { get; set; }
        public virtual ICollection<BraintreeCustomerMapping> BraintreeCustomerMappings { get; set; }
        public virtual ICollection<Calling_Request> Calling_Request { get; set; }
        public virtual ICollection<Calling_Request> Calling_Request1 { get; set; }
        public virtual City_Master City_Master { get; set; }
        public virtual Country_Master Country_Master { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<MessageRecipient> MessageRecipients { get; set; }
        public virtual ICollection<MessageRequest> MessageRequests { get; set; }
        public virtual ICollection<MessageRequest> MessageRequests1 { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<ReportUser> ReportUsers { get; set; }
        public virtual ICollection<ReportUser> ReportUsers1 { get; set; }
        public virtual State_Master State_Master { get; set; }
        public virtual ICollection<UserCategoryMapping> UserCategoryMappings { get; set; }
        public virtual ICollection<UserGroupMapping> UserGroupMappings { get; set; }
        public virtual ICollection<UserQuestionSubscribe> UserQuestionSubscribes { get; set; }
        public virtual ICollection<WebSocketSessionDb> WebSocketSessionDbs { get; set; }
    }
}
